### ISSUE TITLE
Custom variant images do not show up in the backend

### ISSUE THREAD

**Issue by pkerling** [FluidTYPO3/fluidcontent_core#131]
They are added to the select list as `<img>` tags in `<option>` tags, which is not supported by HTML(5). Firefox does not show the images at all.

**Comment by Madii** [comment]
Added with https://github.com/FluidTYPO3/fluidcontent_core/commit/b977023a8af9fc18fe40435d1bd13b5a77c4a0ae . Should be now displayed correctly.

**Comment by pkerling** [comment]
Now only the icon for the currently selected variant is shown. I think it would be more useful if an icon was shown for every option entry in the list like it was intended before (but wrongly implemented). It *is* possible to show images in option entries, just not the way it was done before. The easiest way is to use CSS background-image. This is also how the standard TYPO3 fields (CE type, fluid content type) do it.

**Comment by Madii** [comment]
Well it would be nice such display, but that is wasn't standard in Typo3. The select field had never icons. Only the selected one. But let's see :-)

**Comment by jmverges** [comment]
Hi @pkerling,
@Madii is right.

In 6.2 versions core uses:
<option value="text" style="background: #fff url(sysext/t3skin/icons/gfx/i/tt_content.gif) 0% 50% no-repeat; height: 16px; padding-top: 2px; padding-left: 22px;">Text</option>
In 7 > versions (at least 7.3 and master):
<option value="text" data-icon="<img src=&quot;sysext/t3skin/icons/gfx/i/tt_content.gif&quot; alt=&quot;Text&quot; title=&quot;Text&quot; />">Text</option>

I'm not able to see the icons in Safari, Chrome and Opera for 7 and 6.2 versions. However I'm able to see them in 6.2 in Firefox but not in 7 >

I'm going to ask TYPO3 Core members about this feature because it will improve the user experience or at least it will make a more pretty admin ;)

As not is related with FluidTYPO3 I'm going to close this issue. However I was taking a look on Internet and It looks like every body talsk about http://designwithpc.com/plugins/ddslick . You could create an extension for it and share it with the community. I will be glad to use it.

**Comment by pkerling** [comment]
Ah everything makes sense now, I was always using 6.2 in Firefox and took the icons for granted. Safari, Chrome and Opera all use Webkit so I guess it's not supported there. I do think they showed up in IE though. Thanks for the explanation!

**Comment by jmverges** [comment]
You are welcome.
