### ISSUE TITLE
Mailform not working TYPO3 6.2

### ISSUE THREAD

**Issue by SOYOS** [FluidTYPO3/fluidcontent_core#143]
I cannot open the Mailform Wizard and when i open the Page i got this message:

The default controller for extension "FluidcontentCore" and plugin "Mailform" can not be determined. Please check for TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php

**Comment by julianxhokaxhiu** [comment]
Same here but no error, just no visible field. This is because maybe FCC is not supporting tt_content mailform. Is there a way to avoid this ONLY for mailform?

**Comment by Madii** [comment]
Well i don't know if FCC is the problem. Mailform is so old and is using many old functions.
But maybe if you change `function includeLocalLang()`in `class.tx_mailform_pi1_wizicon.php`  to this :
````php
function includeLocalLang()	{
	$llFile = TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('mailform').'locallang.xml';
	$object = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('TYPO3\CMS\Core\Localization\Parser\LocallangXmlParser');
	$LOCAL_LANG = $object->getParsedData($llFile, $GLOBALS['LANG']->lang);
						
	return $LOCAL_LANG;
}
````
...it may work. Because i just tried to install it in TYPO3 7.1 and solved some errors on the way. But it's only a guess. ;-) I am not using it.

**Comment by xf-** [comment]
You can find the answer here:
https://github.com/FluidTYPO3/fluidcontent_core/issues/165#issuecomment-123863721
