### ISSUE TITLE
Static Template could not be selected

### ISSUE THREAD

**Issue by misterboe** [FluidTYPO3/fluidcontent_core#152]
When i install fluidcontent_core and want to select the template its does not get activated in the left column. 

Versions:
        "typo3/cms": "7.*",
        "fluidtypo3/vhs": "dev-master",
        "fluidtypo3/flux": "dev-master",
        "fluidtypo3/fluidpages": "dev-master",
        "fluidtypo3/fluidcontent": "dev-master",
        "fluidtypo3/fluidcontent_core": "dev-master",

**Comment by hirnschmalz** [comment]
I think this is a problem of TYPO3 CMS. And I think the problem are some JS errors - just a guess.
Try to reload the right frame (only the frame!) and than try it again.

Markus

**Comment by NamelessCoder** [comment]
I'm afraid Markus is correct about this one. If you are unable to perform this particular action, that is with 100% certainty a problem of TYPO3 itself - it could be a JS failure due to not cleaning typo3temp, it could be a DB schema failure (for which you don't see an error) because of missing updates for sys_template - and finally, there might be an issue with the browser you use or even the way the vhost is configured (e.g. is your site in a subfolder or not).

The easiest way to eliminate this is to just go through the standard checklist: clean all temp, check for JS errors, 404 etc. in browser console, then go from any errors you find there!

Shouldn't take too long to track it down ;)
