### ISSUE TITLE
Upcoming 7.x with Fluid CE

### ISSUE THREAD

**Issue by mithri** [FluidTYPO3/fluidcontent_core#180]
Hi there,

how will fluidcontent_core work together with the new Fluid CE Elements in TYPO3? Is a migration possible? Or will both systems co-exist in the future? What would you recommend for a new big TYPO3 project?

Thanks
Tobias

**Comment by xf-** [comment]
Hi,

we have no suggestions, because it isn't implemented yet. We read about it:
Jo Hasenau from Gridelements will implement it and plan right now is on a basic/simple level.
If the implementation works for us and has all necessary features in API, we will use it.

For FT3 - we normally provide a update path.

**Comment by NamelessCoder** [comment]
Hi Tobias,

I have only one thing to add to what Xaver already replied - and that is that it looks like the features will be compatible enough that you could actually operate an FCC template as if it were a "Fluid CE" template, and vice versa. The main point of difference seems to be the lack of a flexible controller pattern, the lack of Flux integration (although this can be applied there) and perhaps most notably, the concepts for "variants" and "versions" as introduced by FCC.

Summa summarum: it is quite likely we can get 100% compatibility as well as a completely transparent migration to "Fluid CE" with Flux features.

**Comment by mithri** [comment]
Great, thanks for the information.
