### ISSUE TITLE
TCA Default-Fields like image appearance are lost/broken

### ISSUE THREAD

**Issue by typoworx-de** [FluidTYPO3/fluidcontent_core#189]
After installing fluidcontent_core TCA Default-Fields like image appearance are lost/broken due to this extension!

I figured out that in @Configuration\TCA\Overrides\t_content.php@ are some modifications that remove fields that still make sense.

For example one can't configure image-sizes (f.e. for really large photos useful) or configure image columns and image/text align anymore.

Commenting out these lines makes the "appearance" tab re-appear:
```
$GLOBALS['TCA']['tt_content']['types']['image']['showitem'] = '
                --palette--;LLL:EXT:cms/locallang_ttc.xlf:palette.general;general,
                --palette--;LLL:EXT:cms/locallang_ttc.xlf:palette.header;header,
        --div--;LLL:EXT:cms/locallang_ttc.xlf:tabs.images,
                image,
                --palette--;LLL:EXT:cms/locallang_ttc.xlf:palette.imagelinks;imagelinks,
	    --div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.appearance,
		        --palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.frames;frames,
        --div--;LLL:EXT:cms/locallang_ttc.xlf:tabs.access,
                --palette--;LLL:EXT:cms/locallang_ttc.xlf:palette.visibility;visibility,
                --palette--;LLL:EXT:cms/locallang_ttc.xlf:palette.access;access,
        --div--;LLL:EXT:cms/locallang_ttc.xlf:tabs.extended
';
```

There is to check which modifications are useful and which are not. Same for textimage and may be some other content-elements!

**Comment by typoworx-de** [comment]
I just noticed that previous release version 1.1.3 is not broken yet!

**Comment by NamelessCoder** [comment]
> In some cases I think it may be much better if the site-admin can decide which features he wants to use out of fluidcontent_core and which one not (until missing features are implemented like text+image alignment, click-enlarge checkbox for lightbox, image-cols/rows to align multiple images in one block ...)

That would be the CSS styled content way - the exact opposite of our way.

What they do is ship every conceivable rendering and let you configure it.

What we do is ship the most basic usable rendering and let you extend it.

So where in CSS styled content you *remove* all the things you don't need, in FCC you *add* whatever you do need. It does take a bit of mental adjustment to not repeatedly think "why is this not shipped?" because in almost every single case, the answer is "because it shouldn't be".

Please also study the (fairly long) history of what is actually going on currently in the TYPO3 core in terms of decoupling CSC from the core. Once you know what the goals are and what is being done to get there, you should see it all making sense - including why FCC currently has to *remove* these fields, leading to misunderstandings like the one above.

> This should be configureable within extension-configuration.

We respectfully but completely disagree. It should be extendable with overrides on top of a minimal configuration.

**Comment by typoworx-de** [comment]
Thanks for feedback. I discovered your plugin an bit and now figured it out.

On the other hand in some usecases it may be useful to fallback for typo3-developers since TYPO3 content-editors and developers as well are used to use features like image-appearance to align images and so on.

I really like the way fluidcontent does switch to fluid-templating as alternative to CSC, but we have to investigate to get well known and useful features working there as well.

```
We respectfully but completely disagree. It should be extendable with overrides on top of a minimal configuration.
```
I partly agree... but then you should unot UNSET TCA-Fields in PHP but use TsConfig instead to disable them (which makes them re-activable by users without having to poke with PHP and another override).
