### ISSUE TITLE
Settings override in multi site installation doesn't work.

### ISSUE THREAD

**Issue by Ishikawakun** [FluidTYPO3/fluidcontent_core#210]
This issue is hard to describe.

I overwrote the fluidcontent_core settings for the container classes in content_options on a multi site installation. The changes were only supposed to be for one of the sites so i put them inside the template.
The template also showed the correct values.

The FlexForms though did not seem to be able to read the values from the template.

Only when i added the same TypoScript to the template on the page with uid = 1 did the backend FlexForm find my settings. It would seem that somewhere when generating the FlexForms from Flux templates the "scope" does not respect the current page template.

Possibly not a bug as the FlexForms are probably generated in some kind of global scope. 

But still at the very least annoying, as i did not find a mention of this anywhere.

**Comment by NamelessCoder** [comment]
I'm sorry to report that this will indeed tend to happen when reading TypoScript in the backend. The primary reason for that problem is the way Extbase's ConfigurationManager resolves TypoScript - it requires a page UID and does not fully cover every way to resolve that page UID (for example from GET arguments when editing a record, when in list mode, etc). When it is incapable of resolving a page UID the ConfigurationManager will default to resolving *the first detected root TypoScript template as determined by enabled status and creation order with the first created template having first priority*.

So although Flux and FluidcontentCore actually *do* get evaluated in a local scope, that scope is not resolved correctly and both extensions (and any other Extbase-based extension) receive unexpected TypoScript values.

I have to refer you to the [TYPO3 core bug tracker](https://forge.typo3.org/projects/typo3cms-core/issues) to create an issue describing the exact case when those settings do not get resolved correctly (for example: when you edit content records, when you create new content records, where you create new content records like top column, relative to other, as nested element and so on, whether or not you create them in a translated page, in a workspace - as detailed as possible).
