### ISSUE TITLE
GridViewHelper was removed from Flux v8.*

### ISSUE THREAD

**Issue by iamandrewluca** [FluidTYPO3/fluidcontent_core#231]
I have installed
```
"fluidtypo3/fluidcontent_core": "dev-development",
"fluidtypo3/flux": "^8.2"
```

Now adding a image error is thrown
```
#1289386765: Could not analyse class: "FluidTYPO3\Flux\ViewHelpers\Widget\GridViewHelper" maybe not loaded or no autoloader? Class FluidTYPO3\Flux\ViewHelpers\Widget\GridViewHelper does not exist (More information)
```

https://github.com/FluidTYPO3/fluidcontent_core/blob/5f17169f8505320462ad0133126c9f93929480d6/Resources/Private/Templates/CoreContent/Image.html#L33

**Comment by tantegerda1** [comment]
The [`composer.json`](https://github.com/FluidTYPO3/fluidcontent_core/blob/development/composer.json#L8) of this project loosely specifies it depends on flux. Contrary, the [`ext_emconf.php`](https://github.com/FluidTYPO3/fluidcontent_core/blob/development/ext_emconf.php#L39) nails the dependency down to Flux 7.2 to 7.3. So I think, the `composer.json` is wrong and you must actually use a Flux between 7.2 and 7.3 (which is old.) 

---
Actually, I believe this extension is somehow abandoned - and superseded by `fluid_styled_content` from the TYPO3 core (since TYPO3 7 LTS).
See this comments:

https://github.com/FluidTYPO3/fluidcontent_core/issues/228#issuecomment-255466014
> […] after the release of fluid_styled_content this extension is more or less abandoned.

https://github.com/FluidTYPO3/fluidcontent_core/issues/228#issuecomment-255620409
> […] One of these days I expect fluidcontent_core will be abandoned […]

The [last commit](https://github.com/FluidTYPO3/fluidcontent_core/commit/5f17169f8505320462ad0133126c9f93929480d6) in _this_ repository has been made around a year ago, the last [release](https://github.com/FluidTYPO3/fluidcontent_core/releases) is almost two years back.
I would recommend to migrate to `fluid_styled_content` from the core.
---
Disclaimer: I am no insider, I just use and watch FluidTYPO3 development loosely.

**Comment by iamandrewluca** [comment]
Thanks for feedback!

**Comment by NamelessCoder** [comment]
@tantegerda1 is completely correct - and thanks for answering ;)

The only thing I can add is we're working on creating an integration between Flux and Fluid Styled Content - which would be functionally identical to fluidcontent_core with just minor differences in template structure (because FSC chose a slightly different markup strategy). Until that's ready you'll have to make do without Flux forms for the native types - but you'll of course still have them with Flux-registered elements.
